# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 40, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(290, 70, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 100, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 0, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(90, 130, 521, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 330, 81, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(100, 330, 31, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 380, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 380, 491, 21))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 330, 81, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuLanguages = QtWidgets.QMenu(self.menuOption)
        self.menuLanguages.setObjectName("menuLanguages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_the_author = QtWidgets.QAction(MainWindow)
        self.actionAbout_the_author.setObjectName("actionAbout_the_author")
        self.actionAbout_the_program = QtWidgets.QAction(MainWindow)
        self.actionAbout_the_program.setObjectName("actionAbout_the_program")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRandomly = QtWidgets.QAction(MainWindow)
        self.actionRandomly.setObjectName("actionRandomly")
        self.actionEnter_manually = QtWidgets.QAction(MainWindow)
        self.actionEnter_manually.setObjectName("actionEnter_manually")
        self.actionRandomly_2 = QtWidgets.QAction(MainWindow)
        self.actionRandomly_2.setObjectName("actionRandomly_2")
        self.actionBlock_diagram = QtWidgets.QAction(MainWindow)
        self.actionBlock_diagram.setObjectName("actionBlock_diagram")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionEnglish = QtWidgets.QAction(MainWindow)
        self.actionEnglish.setObjectName("actionEnglish")
        self.actionInstruction_manual = QtWidgets.QAction(MainWindow)
        self.actionInstruction_manual.setObjectName("actionInstruction_manual")
        self.menuMenu.addAction(self.actionAbout_the_author)
        self.menuMenu.addAction(self.actionAbout_the_program)
        self.menuMenu.addAction(self.actionInstruction_manual)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionExit)
        self.menuLanguages.addAction(self.action_2)
        self.menuLanguages.addAction(self.actionEnglish)
        self.menuOption.addAction(self.actionRandomly)
        self.menuOption.addAction(self.actionEnter_manually)
        self.menuOption.addAction(self.actionRandomly_2)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionBlock_diagram)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.menuLanguages.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sort string"))
        self.pushButton.setText(_translate("MainWindow", "Read from file"))
        self.pushButton_2.setText(_translate("MainWindow", "Enter manually"))
        self.pushButton_3.setText(_translate("MainWindow", "Accidentally"))
        self.label.setText(_translate("MainWindow", "Choose a matrix filling method:"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "Select row:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", "Sorted string:"))
        self.pushButton_5.setText(_translate("MainWindow", "Let\'s sort"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuLanguages.setTitle(_translate("MainWindow", "Languages"))
        self.actionAbout_the_author.setText(_translate("MainWindow", "About the author"))
        self.actionAbout_the_program.setText(_translate("MainWindow", "About the program"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRandomly.setText(_translate("MainWindow", "Read from file"))
        self.actionEnter_manually.setText(_translate("MainWindow", "Enter manually"))
        self.actionRandomly_2.setText(_translate("MainWindow", "Accidentally"))
        self.actionBlock_diagram.setText(_translate("MainWindow", "Block diagram"))
        self.action_2.setText(_translate("MainWindow", "Русский"))
        self.actionEnglish.setText(_translate("MainWindow", "English"))
        self.actionInstruction_manual.setText(_translate("MainWindow", "Instruction manual"))
